### ISSUE TITLE
File already exists failure

### ISSUE THREAD

**Issue by usma0118** [Benni-chan/nzbToAniDB#25]
Failure in case of file already exists:

Traceback (most recent call last):
  File "./anidb.py", line 352, in <module>
    shutil.move(file.name, os.path.join(path,filename))
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 98, in copystat
    os.utime(dst, (st.st_atime, st.st_mtime))
OSError: [Errno 1] Operation not permitted: /destination

**Comment by Benni-chan** [comment]
thanks for reporting.
on which operating system are you?
as far as I remember, overwriting an existing file should work.
but I'll check

**Comment by usma0118** [comment]
Using Ubuntu 20.04
